### ISSUE TITLE
Asset files should have friendly names

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring-assets#1]
It's been agreed that we should introduce 'friendly' file names for assets, (as opposed to the generated hash). 

Assets are currently stored in two nested folders according to their hashed name, so it's unlikely that clashes will occur, but this system feels a bit illogical and clunky at times (I believe this was originally done as the intention was to only ever store one copy of a single file -- if a file was uploaded twice, both metadata 'assets' pointed to the same physical file). 

Other possibilities:
- Introduce a 'friendly' name on the DB metadata, and use this whenever writing the file
- Change the nested system (possibly to use the asset's _id?)

**Comment by memeteli** [comment]
I think we should have a discussion about this.

**Comment by taylortom** [comment]
This one is undecided. The big negative to introducing user-specified filenames is that users are then required to make sure there are no duplicate names. One possible way to do this is to just set the file name attribute as unique in mongodb, and let mongodb send an error if there are multiple matches.

**Comment by taylortom** [comment]
Won't fix
